//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainBoard
    {
        public int mainBoardNo { get; set; }
        public string category { get; set; }
        public string userID { get; set; }
        public string id_Name { get; set; }
        public string mainBoardTitle { get; set; }
        public string mainBoardContent { get; set; }
        public System.DateTime writeDate { get; set; }
        public string mainBoardPwd { get; set; }
    
        public virtual UserInfor UserInfor { get; set; }
    }
}
